/* src/libjasper/include/jasper/jas_config.h.  Generated by configure.  */
/* src/libjasper/include/jasper/jas_config.h.in.  Generated from configure.ac by autoheader.  */


/* Avoid problems due to multiple inclusion. */
#ifndef JAS_CONFIG_H
#define JAS_CONFIG_H

/* This preprocessor symbol identifies the version of JasPer. */
#define	JAS_VERSION "2.0.33"
/* If configure is being used, this symbol will be defined automatically
  at this point in the configuration header file. */


#define JAS_INCLUDE_JP2_CODEC 1
#define JAS_INCLUDE_JPC_CODEC 1
/* #define JAS_INCLUDE_JPG_CODEC 1 */
#define JAS_INCLUDE_PGX_CODEC 1


/* The preprocessor symbol JAS_WIN_MSVC_BUILD should not be defined
  unless the JasPer software is being built under Microsoft Windows
  using Microsoft Visual C. */
#if (defined(_MSC_VER) || defined(_VISUALC_)) && !defined(JAS_WIN_MSVC_BUILD)
# define JAS_WIN_MSVC_BUILD
#endif
#if defined(JAS_WIN_MSVC_BUILD)
# pragma warning(disable : 4013)
# pragma warning(disable : 4018)
# pragma warning(disable : 4244)
# pragma warning(disable : 4715)
#endif
#if !defined(JAS_WIN_MSVC_BUILD)
/* A configure-based build is being used. */



/* Extra debugging support */
/* #undef DEBUG */

/* Debugging memory allocator */
/* #undef DEBUG_MEMALLOC */

/* Debugging overflow detection */
/* #undef DEBUG_OVERFLOW */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you don't have `vprintf' but do have `_doprnt.' */
/* #undef HAVE_DOPRNT */

/* Define to 1 if you have the <fcntl.h> header file. */
#define JAS_HAVE_FCNTL_H 1

/* Define to 1 if you have the `getrusage' function. */
#define JAS_HAVE_GETRUSAGE 1

/* Define to 1 if you have the `gettimeofday' function. */
#define JAS_HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define JAS_HAVE_INTTYPES_H 1

/* Define to 1 if you have the <io.h> header file. */
/* #undef HAVE_IO_H */

/* Define to 1 if you have the `m' library (-lm). */
#define JAS_HAVE_LIBM 1

/* Define to 1 if you have the <limits.h> header file. */
#define JAS_HAVE_LIMITS_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define JAS_HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdbool.h> header file. */
#define JAS_HAVE_STDBOOL_H 1

/* Define to 1 if you have the <stddef.h> header file. */
#define JAS_HAVE_STDDEF_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define JAS_HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define JAS_HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define JAS_HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define JAS_HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define JAS_HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define JAS_HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define JAS_HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define JAS_HAVE_UNISTD_H 1

/* Have variable length arrays */
#define JAS_HAVE_VLA 1

/* Define to 1 if you have the `vprintf' function. */
#define JAS_HAVE_VPRINTF 1

/* Define to 1 if you have the <windows.h> header file. */
/* #undef HAVE_WINDOWS_H */

/* JasPer configure */
#define JAS_CONFIGURE 1

/* JasPer version */
#define JAS_VERSION "2.0.33"

/* Name of package */
#define PACKAGE "jasper"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "jasper"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "jasper 2.0.33"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "jasper"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.0.33"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "2.0.33"

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to `long long' if <sys/types.h> does not define. */
#define longlong long long

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef ssize_t */

/* Define to `unsigned char' if <sys/types.h> does not define. */
#define uchar unsigned char

/* Define to `unsigned int' if <sys/types.h> does not define. */
/* #undef uint */

/* Define to `unsigned long' if <sys/types.h> does not define. */
/* #undef ulong */

/* Define to `unsigned long long' if <sys/types.h> does not define. */
#define ulonglong unsigned long long

/* Define to `unsigned short' if <sys/types.h> does not define. */
/* #undef ushort */


#else
/* A configure-based build is not being used. */
#include <jasper/jas_config2.h>
#endif


#if !defined(JAS_DEC_DEFAULT_MAX_SAMPLES)
#define JAS_DEC_DEFAULT_MAX_SAMPLES (64 * ((size_t) 1048576))
#endif

#if defined(__GNUC__) && !defined(__clang__)
#define JAS_ATTRIBUTE_DISABLE_USAN \
  __attribute__((no_sanitize_undefined))
#elif defined(__clang__)
#define JAS_ATTRIBUTE_DISABLE_USAN \
  __attribute__((no_sanitize("undefined")))
#else
#define JAS_ATTRIBUTE_DISABLE_USAN
#endif


#ifdef _DLL
 //#define JAS_DLL		// I do not understand how this could help.
#endif
#include "jas_compiler.h"
#include "jas_dll.h"


#include "jas_types.h"

#endif
